apiVersion: v1
kind: Service
metadata:
  name: elohim-site-service
  namespace: elohim-prod
spec:
  selector:
    app: elohim-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
