[package]
name = "content_store"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "content_store"

[dependencies]
hdk.workspace = true
serde.workspace = true
content_store_integrity = { path = "../content_store_integrity" }
