apiVersion: v1
kind: ConfigMap
metadata:
  name: elohim-config-alpha
  namespace: elohim-alpha
data:
  config.json: |
    {
      "logLevel": "debug",
      "environment": "alpha",
      "doorwayUrl": "https://doorway-alpha.elohim.host"
    }
