apiVersion: v1
kind: Service
metadata:
  name: elohim-site-staging-service
  namespace: elohim-staging
spec:
  selector:
    app: elohim-site-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
