#TODO separate staging/production ingress separate CI/CD to safely handle potential breaking ingress configurations.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elohim-site-ingress
  namespace: ethosengine
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: public
  rules:
  - host: elohim.host
    http:
      paths:
      - backend:
          service:
            name: elohim-ui-playground-service
            port:
              number: 80
        path: /ui-playground
        pathType: Prefix
      - backend:
          service:
            name: elohim-site-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: staging.elohim.host
    http:
      paths:
      - backend:
          service:
            name: elohim-ui-playground-staging-service
            port:
              number: 80
        path: /ui-playground
        pathType: Prefix
      - backend:
          service:
            name: elohim-site-staging-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: alpha.elohim.host
    http:
      paths:
      - backend:
          service:
            name: elohim-ui-playground-alpha-service
            port:
              number: 80
        path: /ui-playground
        pathType: Prefix
      - backend:
          service:
            name: elohim-site-alpha-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - elohim.host
    secretName: elohim-site-tls-cert
  - hosts:
    - staging.elohim.host
    secretName: staging-elohim-site-tls-cert
  - hosts:
    - alpha.elohim.host
    secretName: alpha-elohim-site-tls-cert