apiVersion: v1
kind: Service
metadata:
  name: elohim-site-service
  namespace: ethosengine
spec:
  selector:
    app: elohim-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: elohim-site-staging-service
  namespace: ethosengine
spec:
  selector:
    app: elohim-site-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: elohim-site-alpha-service
  namespace: ethosengine
spec:
  selector:
    app: elohim-site-alpha
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: elohim-ui-playground-service
  namespace: ethosengine
spec:
  selector:
    app: elohim-ui-playground
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: elohim-ui-playground-staging-service
  namespace: ethosengine
spec:
  selector:
    app: elohim-ui-playground-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: elohim-ui-playground-alpha-service
  namespace: ethosengine
spec:
  selector:
    app: elohim-ui-playground-alpha
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP