apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elohim-site-alpha-ingress
  namespace: elohim-alpha
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: public
  rules:
  - host: alpha.elohim.host
    http:
      paths:
      - backend:
          service:
            name: elohim-ui-playground-alpha-service
            port:
              number: 80
        path: /ui-playground
        pathType: Prefix
      - backend:
          service:
            name: elohim-site-alpha-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - alpha.elohim.host
    secretName: alpha-elohim-site-tls-cert
