apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elohim-site-ingress
  namespace: elohim-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: public
  rules:
  - host: elohim.host
    http:
      paths:
      - backend:
          service:
            name: elohim-site-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - elohim.host
    secretName: elohim-site-tls-cert
