[package]
name = "imagodei_integrity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "imagodei_integrity"

[dependencies]
hdi.workspace = true
holochain_serialized_bytes.workspace = true
serde.workspace = true
